image: "${ruby}"

cache:
  key: "${CI_COMMIT_REF_SLUG}-${ruby}"
  paths: [ "vendor/ruby", "gemfiles/vendor/ruby" ]

before_script:
  - ruby -v
  - bundle config set path "vendor/ruby"
  - bundle config set without development
  - bundle install --jobs $(nproc)

.test:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'

# Rubocop ######################################################################

rubocop:
  extends:   .test
  variables: { ruby: "ruby:3.2" }
  script:    bundle exec rubocop

# RSpec ########################################################################

rspec:
  extends:   .test
  services:  [ "${redis}" ]
  variables: { REDIS_URL: "redis://redis:6379" }
  script:    bundle exec rspec
  parallel:
    matrix:
      - redis: [ "redis:6.0", "redis:6.2", "redis:7.0" ]
        ruby:  [ "ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:3.2", "jruby:9.4" ]
        BUNDLE_GEMFILE:
          - gemfiles/sidekiq_7.0.x.gemfile
          - gemfiles/sidekiq_7.1.x.gemfile
