= Sidekiq::Pauzer


== Installation

Add this line to your application's Gemfile:

    $ bundle add sidekiq-pauzer

Or install it yourself as:

    $ gem install sidekiq-pauzer


== Usage

[source, ruby]
----
require "sidekiq"
require "sidekiq/pauzer"

Sidekiq::Pauzer.configure do |config|
  # Set paused queues local cache refresh rate in seconds.
  # Default: 5.0
  config.refresh_rate = 10.0
end
----

When running in forked environment (e.g., Puma web server), you also need to
call `Sidekiq::Pauzer.startup` on fork:

[source, ruby]
----
# file: config/puma.rb
on_worker_boot { Sidekiq::Pauzer.startup }
----

=== API

This gem enhances Sidekiq's Queue API with:

[source, ruby]
----
Sidekiq::Queue.new("critical").paused? # => true|false
Sidekiq::Queue.new("critical").pause!
Sidekiq::Queue.new("critical").unpause!
----

Those translates to:

[source, ruby]
----
Sidekiq::Pauzer.paused?("critical") # => true|false
Sidekiq::Pauzer.pause!("critical")
Sidekiq::Pauzer.unpause!("critical")
----

=== Adding Pause/Resume Button to the Queues Tab

If you're not overriding `Sidekiq::Web.views` path, then you can override
default queues tab with:

[source, ruby]
----
require "sidekiq/web"
require "sidekiq/pauzer/web"
----

NOTE: If you are using custom Sidekiq views path, then you will need to call
  (after requiring `sidekiq/pauzer/web`): `Sidekiq::Pauzer::Web.unpatch_views!`.


== Supported Ruby Versions

This library aims to support and is tested against the following Ruby versions:

* Ruby 3.0.x
* Ruby 3.1.x
* Ruby 3.2.x

If something doesn't work on one of these versions, it's a bug.

This library may inadvertently work (or seem to work) on other Ruby versions,
however support will only be provided for the versions listed above.

If you would like this library to support another Ruby version or
implementation, you may volunteer to be a maintainer. Being a maintainer
entails making sure all tests run and pass on that implementation. When
something breaks on your implementation, you will be responsible for providing
patches in a timely fashion. If critical issues for a particular implementation
exist at the time of a major release, support for that Ruby version may be
dropped.


== Supported Sidekiq Versions

This library aims to support and work with following Sidekiq versions:

* Sidekiq 7.2.x


== Development

  bundle install
  bundle exec appraisal generate
  bundle exec appraisal install
  bundle exec rake


== Contributing

* Fork sidekiq-pauzer
* Make your changes
* Ensure all tests pass (`bundle exec rake`)
* Send a merge request
* If we like them we'll merge them
* If we've accepted a patch, feel free to ask for commit access!
