#!/usr/bin/env bash

set -Eeuxo pipefail

# sidekiq-6.5.x depends on redis-rb, but supports redis-client
for REDIS_GEM in redis redis-namespace redis-client; do
  export BUNDLE_GEMFILE="gemfiles/sidekiq_6.5.x.gemfile"
  export REDIS_GEM="${REDIS_GEM}"
  bundle check || bundle install
  bundle exec rspec "$@"
done

# As of sidekiq-7.0.0, it depends on, and supports only redis-client
for BUNDLE_GEMFILE in gemfiles/sidekiq_7.*.gemfile; do
  export BUNDLE_GEMFILE="${BUNDLE_GEMFILE}"
  export REDIS_GEM="redis-client"
  bundle check || bundle install
  bundle exec rspec "$@"
done
