# frozen_string_literal: true

source "https://rubygems.org"

gem "base64"
gem "irb"
gem "json"
gem "logger"
gem "puma"
gem "rack"
gem "rack-session"
gem "sidekiq"
gem "sidekiq-pauzer", path: ".."
gem "sinatra"
