name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUNDLE_WITHOUT: "development"
  JRUBY_OPTS: "--dev --debug"

jobs:
  test:
    name: "rspec (ruby:${{ matrix.ruby }}"

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        ruby: [ ruby-3.0, ruby-3.1, ruby-3.2 ]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: RSpec
        run: scripts/ci-rspec

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.2
          bundler-cache: true

      - name: bundle exec rubocop
        run: bundle exec rubocop --format progress --color
